### ISSUE TITLE
找不到javafx.scene.control.Dialog的类文件

### ISSUE THREAD

**Issue by zwxbest** [spawpaw/mybatis-generator-gui-extension#1]
H:\下载\mybatis-generator-gui-extension-master\src\main\java\com\spawpaw\mybatis\generator\gui\controller\BaseController.java
Error:(82, 14) java: 无法访问javafx.scene.control.Dialog
  找不到javafx.scene.control.Dialog的类文件

**Comment by spawpaw** [comment]
请检查一下你的JDK版本，最低JDK 8u40
