### ISSUE TITLE
一点击表则原先配置好的实体名等相关的名称都会重新变

### ISSUE THREAD

**Issue by benjazHuang** [spawpaw/mybatis-generator-gui-extension#10]
比如曾经为一个表名为orderdetail的表设置了实体名OrderDetail，但下次重新进来生成时一点表，这时实体名变成了Orderdetail，这个不太好。
不过目前有个解决方法就是选择表后，再在表json列表中切换就好了。

**Comment by spawpaw** [comment]
这个功能我也考虑过，但是当表结构发生改变的时候，原来的配置肯定还是要失效的。

推荐表名和字段名全部为字母+下划线命名，这样对象名就会自动转换为大骆驼峰（有的数据库表名在传输的时候会全部转换成小写，所以程序没办法识别你的命名格式）

**Comment by benjazHuang** [comment]
我现在是先选择表名，再选择对应的配置项就行了，这个我想不用改了，谢谢
