### ISSUE TITLE
能不能加个开关控制generator不要生成默认的注释

### ISSUE THREAD

**Issue by benjazHuang** [spawpaw/mybatis-generator-gui-extension#11]
mybatis generator默认生成的那些注释看着实在不好，也没必要，我对mybatis generator不熟，但找了一下好像是有开关的，能不能麻烦作者给做个开关控制一下。
https://blog.csdn.net/MrShen_XC/article/details/76451723

**Comment by spawpaw** [comment]
如果开启注释插件就不会生成MBG的默认注释了，近期会加上关闭MBG默认注释的开关

**Comment by benjazHuang** [comment]
好的，也是个解决办法，你辛苦了，打赏了5块钱请你喝瓶水

**Comment by spawpaw** [comment]
谢谢~
