### ISSUE TITLE
请问一下有批量生成功能吗？

### ISSUE THREAD

**Issue by prlei** [spawpaw/mybatis-generator-gui-extension#12]
hi, 好酷的工具，请问一下有批量生成功能吗？
例如：我只想去表前缀，剩下其他默认批量生成库里所有表，比如我50张表没有特殊需求也要一个一个的配置。

**Comment by jiffei** [comment]
同问，有批量生成功能吗？

**Comment by spawpaw** [comment]
批量生成功能已添加，下载最新代码并运行，点击生成代码按钮右侧的小箭头即可看到批量生成选项

**Comment by prlei** [comment]
cool, we obviously appreciate you very much.

**Comment by prlei** [comment]
sorry,没有找到。只有“生成代码”和“保存配置”，我下的是gui-extension-v2.4.0-stable-jar-with-dependencies.jar

**Comment by spawpaw** [comment]
我的意思是直接通过代码运行，最新版的jar包还没有发布

**Comment by prlei** [comment]
好象不行哎。。。我是mac系统，jar包版本，能正常生成一张表，但是代码版本：
我要不新建 java和resources目录会提示两个目录不存在：
---The specified target projec xxxxxx/src/main/resources does not exist
我要新建了java和resources目录：
---Existing file xxxxx/src/main/java/com/ddpsu/security/entity/AreaExample.java was overwritten
以上是点击生成全部时发生的。
建议：
1. 控制新建目录，有就覆盖，没有就新建
2. 所谓一键新建选中表功能，反正我在mac上没用明白，也就是不会多选，还是只能每次选一张

**Comment by prlei** [comment]
现在是源码可用了么？新jar还没放出来？ 坐等jar

**Comment by spawpaw** [comment]
上次一边发布新release一边和妹子聊天,结果版本号打错了,这次我要选个好日子再发布

**Comment by prlei** [comment]
我竟无言以对啊，如此严肃的事情，给出这么吊的理由，我给你82分，6爆了。
坐等出jar，close问题，哈··！
你不是因为想和我聊天，才故意不发布，然后我好不能close问题，心机。。。。
