### ISSUE TITLE
还建议曾加一个选项，只生成model/mapper/dao（多选）

### ISSUE THREAD

**Issue by jiffei** [spawpaw/mybatis-generator-gui-extension#14]
还建议曾加一个选项，只生成model/mapper/dao（多选）

**Comment by spawpaw** [comment]
个人认为，重新生成的时候，大都是因为更改了数据库，这时候model/dao/xml都需要重新生成，
所以单独生成某一个层的代码的情况并不常见，所以不太愿意增加这个选项，不知这个功能有没有哪些独特的应用场景？

**Comment by jiffei** [comment]
比如数据库改了字段，dao并不要重新生成，dao里面有可能已经添加了新方法，重新生成，新方法又要重新，或者能覆盖生成也可以。
还有mapper.xml覆盖有bug，旧的字段还是在里面，sql也会生成两份一样的。

**Comment by spawpaw** [comment]
关于mapper的重复生成问题，是由于关闭了mybatis generator默认注释功能引起的，参见[MBG/issues/311](https://github.com/mybatis/generator/pull/311)。

默认的注释生成插件会生成`@mbg.generated`tag,这样MBG在重新生成时就会覆盖原有的，保留手工添加的。然而我自己写的注释插件里面没有加上这个tag（加上之后代码有些难看，参见issue #11 ）。
我觉得在注释中添加`@mbg.generated`比单独生成某一个层的代码更好一些，这样在重新生成代码的时候只会自动覆盖之前自动生成的代码（添加了`@mbg.generated`tag的方法/字段）。等到下一个MBG版本发布的时候再加上完全覆盖xml的开关。
何如？

**Comment by wzzjdsl** [comment]
我的建议是自动生成的代码不要修改，新增方法也一样。可以重新写一个 *ExtMapper.xml
