### ISSUE TITLE
建议一些优化项

### ISSUE THREAD

**Issue by WuGuozhi** [spawpaw/mybatis-generator-gui-extension#16]
rootClass 属性

还有就是自定义查询方法的问题，作者有什么好的解决方案不？

**Comment by spawpaw** [comment]
MBG在重新生成时，可以直接覆盖或者只重新生成在注释中添加了`@mbg.generated`的方法。目前只支持直接覆盖原有文件，两天内发布新版本，之后可以将自定义查询直接写在mapper中，再次生成时只会覆盖之前自动生成的代码。
