### ISSUE TITLE
数据连接中的表不是按表名排序的吗？

### ISSUE THREAD

**Issue by xvpindex** [spawpaw/mybatis-generator-gui-extension#2]
你好，你的MBG很好用，谢谢你的分享！只是有一个小问题，我在连接数据库后，显示出来的数据表不是按表名排序的，找表很费劲，这个功能能实现吗？

**Comment by spawpaw** [comment]
已经在刚刚的commit里添加了表排序的代码，现在连接数据库之后，表列表会根据字典序自动排列
