### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by CQLiuhuan** [spawpaw/mybatis-generator-gui-extension#20]
可以在mapper中添加批量添加和批量修改的方法嘛？用foreach的形式，这样就完美呢。

**Comment by spawpaw** [comment]
批量添加的已经有了，在`DAO设置`->`启用批量插入插件  `，会生成`batchInsert`和`batchInsertSelective`方法
批量修改的话，可以试试updateByExample或者直接外循环？

**Comment by CQLiuhuan** [comment]
批量添加，之前没太注意有此选项，现在已可以使用。但是使用发现一点小问题，生成的xml sql中，如果是数据库关键字, 未进行特殊处理，如 `desc` 。
