### ISSUE TITLE
生成JPA注解部分注解没有生成

### ISSUE THREAD

**Issue by quqiangsheng** [spawpaw/mybatis-generator-gui-extension#22]
## I'm submitting a...

- [x] Bug report (BUG 报告)  

## Current behavior

com.spawpaw.mybatis.generator.gui.plugin.CommentPlugin.addFieldAnnotation(Field, IntrospectedTable, IntrospectedColumn, Set<FullyQualifiedJavaType>)
CommentPlugin类357行该方法在生成代码时即使勾选了生成jpa注解也不会有效
2.5.4

## Expected behavior

我需要标准的jpa@Id 和我自己修改后加上的@Column注解 发现根本走不到这个方法 另外建议源码直接提供@Column注解 大部分如果需要用jpa标准的话这个是很需要

## Environment

JDK Version:
- [x] OracleJDK 8u40+
- [ ] OpenJDK 8+ with openjfx

Database:
- [x] MySQL/MariaDB
- [ ] Oracle
- [ ] SQL Server
- [ ] input your database name

**Comment by spawpaw** [comment]
最近有点忙，可能不能及时修复这个BUG（不过肯定会在一周之内解决）

如果等不及的话可以自己先修改CommentPlugin，然后发起pull request，我们一起完善这个项目。
