### ISSUE TITLE
新建连接保存不了，提示保存失败：data\connection\test.json（系统找不到指定路径。）

### ISSUE THREAD

**Issue by liugdxd** [spawpaw/mybatis-generator-gui-extension#27]
## I'm submitting a...

- [x] Bug report (BUG 报告)  
- [ ] Feature request (功能建议)
- [ ] Documentation issue or request (文档相关)

## Environment

JDK Version:
- [x] OracleJDK 8u40+
- [ ] OpenJDK 8+ with openjfx

Database:
- [x] MySQL/MariaDB
- [ ] Oracle
- [ ] SQL Server
- [ ] others 
 
Others:

**Comment by spawpaw** [comment]
在测试时都能正常保存，并没有出现上述问题。
是不是程序所在目录没有写权限？
