### ISSUE TITLE
Mysql 8.0 无法使用

### ISSUE THREAD

**Issue by Gahon1995** [spawpaw/mybatis-generator-gui-extension#28]
## I'm submitting a...

- [ √] Bug report (BUG 报告)  

## BUG
使用mysql8.0的时候无法连接，需要在url上加上timezone才能够连接上，但是连接上以后无法获取到表列表，双击左边数据库连接报错如下：

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'HAVING TABLE_TYPE IN ('TABLE','VIEW',null,null,null) ORDER BY TABLE_TYPE, TABLE_' at line 1

**Comment by spawpaw** [comment]
BUG已修复，可下载最新版本使用~
