### ISSUE TITLE
建议MYSQL TINYINT(1)  字段 映射为Boolean

### ISSUE THREAD

**Issue by darren-fu** [spawpaw/mybatis-generator-gui-extension#29]
## I'm submitting a...

-  Feature request (功能建议)

## Current behavior

目前MYSQL TINYINT(1)  字段 映射到java entity是 Byte类型

## Expected behavior

建议映射为 Boolean类型，因为已经指定了长度为1

**Comment by spawpaw** [comment]
在本地测试时，当数据类型为tinyint(1)的时候生成的实体类是boolean型。
是不是你的数据库里误写成了tinyint(4)？

**Comment by darren-fu** [comment]
可能是版本问题，我更新一下最新版本试试
