### ISSUE TITLE
Ben大神您好，Service层如何自动生成？

### ISSUE THREAD

**Issue by longlearngo** [spawpaw/mybatis-generator-gui-extension#32]
项目介绍中写到可以生成Service，但图形界面中未找到相关配置，生成代码中也未找到Service代码，请指教谢谢

**Comment by spawpaw** [comment]
可以在`MVC*代码生成`选项卡中打开代码生成功能，不过具体的模版需要自己在`src/main/resources/template`目录下自行编写，然后添加相关配置。

如果需要在模版中引用列名、方法名等，可以参考`src/main/resources/template/test.vm` 这个文件
