### ISSUE TITLE
一个Mysql服务器中,如果有同名的表,列不一致会生成失败

### ISSUE THREAD

**Issue by greydesolate** [spawpaw/mybatis-generator-gui-extension#35]
如题.

**Comment by greydesolate** [comment]
删掉冗余信息.如题.

**Comment by greydesolate** [comment]
删掉冗余信息.如题.

**Comment by spawpaw** [comment]
已修复同一mysql实例中有多个同名表会导致bug的问题
不同的数据库对catlog和schema的支持不同，目前只测试过mysql没有问题，其他数据库仍需测试

**Comment by greydesolate** [comment]
我的锅,我没有描述清楚问题.
比如当前数据库甲,里有表t1字段A,B,C.
比如当前数据库乙,里有表t1字段A,B,C,D
尝试生成乙的t1会报错,说不存在字段D.是因为生成的时候也没有按照数据库甲/乙过滤.

当前修改的只是把UI界面那里呈现出来的其余库的同名表字段过滤了.
但是MybatisGenerator那里真正生成时,也需要过滤,我昨儿晚上也翻阅这项目源码,数据库连接里含有指定的数据库了,但是生成的时候还是会把其余同名表生成,导致看console输出,有几张同名表,输出几次
