### ISSUE TITLE
关闭连接后无法再连接

### ISSUE THREAD

**Issue by taihucao** [spawpaw/mybatis-generator-gui-extension#39]
## I'm submitting a...

- [x] Bug report (BUG 报告)  
- [ ] Feature request (功能建议)
- [ ] Documentation issue or request (文档相关)

## Current behavior

右键关闭连接后，再想连接，无反应

## Expected behavior

希望能关闭后重新连接

## Minimal reproduction of the problem with instructions

关闭后再连接即可复现。
关闭后无法连接时，选择编辑连接，并保存，然后重连，就很正常

## Environment

JDK Version:
- [x] OracleJDK 8u40+
- [ ] OpenJDK 8+ with openjfx

Database:
- [x] MySQL/MariaDB
- [ ] Oracle
- [ ] SQL Server
- [ ] others 
 mysql
Others:

**Comment by spawpaw** [comment]
嗯，现在确实有这个问题...这两天应该就能改好
