### ISSUE TITLE
生成的controller接收的主键参数类型不对

### ISSUE THREAD

**Issue by jasonsuzhou** [spawpaw/mybatis-generator-gui-extension#41]
## I'm submitting a...
- [x] Bug report (BUG 报告)  
- [ ] Feature request (功能建议)
- [ ] Documentation issue or request (文档相关)

## Current behavior
数据库主键字段类型是bigint，对应生成的dao层代码类型是Long，但是controller生成的类型是Integer

## Expected behavior
controller也应该生成Long类型的

## Minimal reproduction of the problem with instructions
```
@RequestMapping(path = "", method = RequestMethod.DELETE)
    @Transactional
    public long deleteBatch(@RequestParam("id") List<Integer> ids) {//这里是integer
        long count = 0;
        for (Integer id : ids) {
            count += mapper.deleteByPrimaryKey(id);//这里接受的Long
        }
        return count;
    }
```

## Environment

JDK Version:
- [x] OracleJDK 8u40+
- [ ] OpenJDK 8+ with openjfx

Database:
- [x] MySQL/MariaDB
- [ ] Oracle
- [ ] SQL Server
- [ ] others 
 
Others:
N/A

**Comment by spawpaw** [comment]
提供的模版仅供参考使用，如果要生成controller、service，建议自己编写模版
