### ISSUE TITLE
There is no file named CommonResponse?

### ISSUE THREAD

**Issue by ukhack** [spawpaw/mybatis-generator-gui-extension#43]
## I'm submitting a...

- [x] Bug report (BUG 报告)  

## Current behavior
releases : gui-extension-for-mbg-v2.5.6-jar-with-dependencies.jar
MVC generator did not generate a file named CommonResponse

## Environment

JDK Version:
- [x] OracleJDK 8u40+

Database:
- [x] MySQL/MariaDB
Others:
Thank for your development

**Comment by spawpaw** [comment]
the sample templates for controller and other layers are just samples, so please write your own service/controller templates to meet your own needs.

**Comment by ukhack** [comment]
> the sample templates for controller and other layers are just samples, so please write your own service/controller templates to meet your own needs.

thx!
