### ISSUE TITLE
在哪里配置表呢

### ISSUE THREAD

**Issue by godchou** [spawpaw/mybatis-generator-gui-extension#45]
## I'm submitting a...

- [ ] Bug report (BUG 报告)  
- [x] Feature request (功能建议)
- [ ] Documentation issue or request (文档相关)

## Environment

JDK Version:
- [x] OracleJDK 8u40+
- [ ] OpenJDK 8+ with openjfx

Database:
- [x] MySQL/MariaDB
- [ ] Oracle
- [ ] SQL Server
- [ ] others 
 
Others:

**Comment by godchou** [comment]
abc

**Comment by spawpaw** [comment]
参见 #44
