### ISSUE TITLE
tableAlias设置不生效

### ISSUE THREAD

**Issue by TTeslar** [spawpaw/mybatis-generator-gui-extension#48]
com/spawpaw/mybatis/generator/gui/util/MBGRunner.java 
164行的代码不生效:
Optional.of(projectConfig.tableAlias).filter(notEmptyStringPropertyPredicate)
                .ifPresent((tableAlias) -> tableConfiguration.addProperty("alias", projectConfig.tableAlias.getValue()));

改为以下代码方可生成带别名的xml:
/* 设置表别名alias */
        Optional.of(projectConfig.tableAlias).filter(notEmptyStringPropertyPredicate)
                .ifPresent((tableAlias) -> tableConfiguration.setAlias(projectConfig.tableAlias.getValue()));

**Comment by spawpaw** [comment]
已修复tableAlias不生效的问题
