### ISSUE TITLE
oracle数据库分页插件有问题

### ISSUE THREAD

**Issue by wzzjdsl** [spawpaw/mybatis-generator-gui-extension#8]
生成oracle数据库的 xxMapper.xml 和 xxExample.java 中的分页逻辑还是 mysql 的版本。关键字 limit

**Comment by spawpaw** [comment]
由于Oracle自身的问题，用MBG自动生成分页代码会非常困难。
推荐使用[Mybatis-PageHelper](https://github.com/pagehelper/Mybatis-PageHelper)进行Oracle的分页操作。

现在的工作重心在自动生成Service/Controller/html方面，短期内（一到两周）不会考虑对Oracle的分页支持。
