### ISSUE TITLE
连接sqlservre非默认实例的时候要如何填写

### ISSUE THREAD

**Issue by reckcn** [spawpaw/mybatis-generator-gui-extension#9]
![image](https://user-images.githubusercontent.com/8858449/37952076-3312927c-31d1-11e8-8c4b-780e5184d621.png)

如上图，连接sqlservre非默认实例的时候要如何填写呢

**Comment by spawpaw** [comment]
连接工具时使用的jdbcUrl为`jdbc:sqlserver://<host>:<port>;databaseName=<dbName>` ，
试试把主机IP填写为`192.168.151.56//DEMO`
